Rules Engine - Edge Firewall_EN
aziontech/docs_en pull request #102
Opened 2021-03-03 15:35 UTC by Luize-boyen

Doc improvement and corrections

2021-03-09 13:12 UTC, rodrigocst requested changes

2021-03-09 13:12 UTC, rodrigocst commented on edge-firewall/rules-engine/index.md
> +- Block;
```suggestion
- Block the request;
```

2021-03-09 13:12 UTC, rodrigocst commented on edge-firewall/rules-engine/index.md
> +    Example.: *Then* *Set Rate Limit*, *Average Rate* *Limit* *(req/s) 2*, *Client IP Address*, *Maximum burst size 10*. In this example, for the Set Rate Limit action, the additional fields Average
Hi Luize!
Here we add the feature of rate-limiting / minute! I suggest you cover this information also at this step.
Thanks!

2021-03-09 14:10 UTC, Luize-boyen commented on edge-firewall/rules-engine/index.md
> +    Example.: *Then* *Set Rate Limit*, *Average Rate* *Limit* *(req/s) 2*, *Client IP Address*, *Maximum burst size 10*. In this example, for the Set Rate Limit action, the additional fields Average
Hi, Rodrigo!
Thanks! I will change it! ;)

2021-03-09 14:15 UTC, Luize-boyen commented on edge-firewall/rules-engine/index.md
> +- Block;
Arrumado! :)

2021-03-10 13:16 UTC, VitorEltz-Azion approved these changes

2021-03-10 13:17 UTC, merged