Network Lists_EN_Fireawall_update
aziontech/docs_en pull request #104
Opened 2021-03-04 18:45 UTC by Luize-boyen

Doc changes and improvements

2021-03-10 13:52 UTC, VitorEltz-Azion approved these changes

2021-03-10 16:02 UTC, VitorEltz-Azion requested changes

2021-03-10 16:02 UTC, VitorEltz-Azion commented on edge-firewall/network-lists/index.md
> +**Network Lists** is the Azion platform feature that allows you to create and manage *allow lists*, *block lists* or even *greylists* based on the user's network or location. With this feature, it is
```suggestion
**Network Lists** is the Azion platform feature that allows you to create and manage *whitelists*, *blacklists* or even *greylists* based on the user's network or location. With this feature, it is possible to prevent different types of attacks to your network, as well as to prevent users with malicious behavior from having access to your applications.
```

2021-03-18 17:22 UTC, rodrigocst approved these changes

2021-03-24 20:58 UTC, wagnerazion approved these changes

2021-03-26 13:25 UTC, merged