edge node update
aziontech/docs_en pull request #109
Opened 2021-03-11 20:59 UTC by Luize-boyen

add new feature

2021-03-11 21:08 UTC, HSantosAzion approved these changes

2021-03-11 21:12 UTC, luizcunhaazion approved these changes

2021-03-11 21:15 UTC, luizcunhaazion requested changes

2021-03-11 21:15 UTC, luizcunhaazion commented on edge-orchestrator/edge-node/index.md
> +   > The logs to run the Edge Orchestrator agent are stored in:  <br>`/var/log/azion/edge-services.log`
/var/log/azion/edge-orchestrator.log

2021-03-12 13:39 UTC, Luize-boyen commented on edge-orchestrator/edge-node/index.md
> +   > The logs to run the Edge Orchestrator agent are stored in:  <br>`/var/log/azion/edge-services.log`
Thanks, Luiz! Corrected!

2021-03-12 13:48 UTC, luizcunhaazion approved these changes

2021-03-18 12:25 UTC, merged