WAF - improvements and review
aziontech/docs_en pull request #112
Opened 2021-03-19 21:42 UTC by Luize-boyen

Ajustes e melhorias na documentação.

2021-03-24 20:59 UTC, wagnerazion approved these changes

2021-03-26 14:39 UTC, rodrigocst requested changes

2021-03-26 14:39 UTC, rodrigocst commented on web-application-firewall/index.md
> +The **Web Application Firewall** (WAF) protects your applications against threats such as SQL Injections, Remote File Inclusion (RFI), Cross-Site Scripting (XSS) and more. WAF scans HTTP and HTTPS re
```suggestion
The **Web Application Firewall** (WAF) protects your applications against threats such as SQL Injections, Remote File Inclusion (RFI), Cross-Site Scripting (XSS), and more. WAF scans HTTP, and HTTPS requests detect and block malicious activities before reaching your infrastructure and without impacting your applications' performance.
```

2021-03-26 14:39 UTC, rodrigocst commented on web-application-firewall/index.md
> +| Counting Mode  | It is used to specify that the WAF should not block any request. Your applications’ traffic will be analyzed and the threats found will only be counted. Use this mode of operation
The squad is adjusting this name from **Counting** to **Learning** and moving it from the WAF Rule Set to the Edge Firewall Rules Engine. It will require changes soon.
@VitorEltz - @wagnerazion

2021-03-26 14:39 UTC, rodrigocst commented on web-application-firewall/index.md
> +| Whitelist Match Zone | It is the *allowlist* itself. It defines the part or field of the request for which the blocking rule is to be disabled. <br>**Path:** the rule id will not be applied to the
```suggestion
| Allowlist Match Zone | It is the *allowlist* itself. It defines the part or field of the request for which the blocking rule is to be disabled. <br>**Path:** the rule id will not be applied to the request path.<br/>**Query String:** the rule id will not be applied to the query string, also called GET arguments. It can be restricted to both the name and the value of the arguments. It is possible to limit the scope of the *allowlist* to a single GET argument using Conditional Query String.<br/>**Request Header:** the rule id will not be applied to the HTTP headers of the request. It can be restricted to both the name and the value of the headers. It is possible to limit the scope of the *allowlist* to a single HTTP header using the Conditional Request Header.<br/>**Request Body:** the rule id will not be applied to the body of a POST, also called POST arguments. It can be restricted to both the name and the value of the arguments. It is possible to limit the scope of the *allowlist* to a single POST argument using Conditional Request Body.<br/>**File Name** (Multipart Body): the rule id will not be applied to the file name in a multipart POST.<br/>**Raw Body:** the rule id will not be applied to the body that was not interpreted from a request, also called an unparsed body. |
```

2021-03-26 18:50 UTC, Luize-boyen commented on web-application-firewall/index.md
> +The **Web Application Firewall** (WAF) protects your applications against threats such as SQL Injections, Remote File Inclusion (RFI), Cross-Site Scripting (XSS) and more. WAF scans HTTP and HTTPS re
Mandou bem @rodrigocst

2021-03-26 18:52 UTC, Luize-boyen commented on web-application-firewall/index.md
> +| Counting Mode  | It is used to specify that the WAF should not block any request. Your applications’ traffic will be analyzed and the threats found will only be counted. Use this mode of operation
Ok. Let me know as soon I can make these changes, right?

2021-03-26 18:53 UTC, Luize-boyen commented
Thanks @rodrigocst and @wagnerazion! 
I think it is ok now! :)

2021-03-26 19:03 UTC, rodrigocst approved these changes

2021-03-26 19:03 UTC, merged