PMK-778-accountsEN updated
aziontech/docs_en pull request #163
Opened 2021-05-24 19:57 UTC by celeste-casali

Improvements required due  to recent questions to our Support team.

2021-05-25 12:18 UTC, ederson-vieira commented on accounts/users-and-teams/2021-01-14-index.md
> +- Log into the [Real-Time Manager](https://sso.azion.com/login). Click on **Users** or **Teams** either on the Account Settings or the Client Account menu, which is on the upper left. You will be dir
The Client Account menu is on upper right.
I can't find the "Account Settings".

2021-05-25 12:20 UTC, ederson-vieira commented on accounts/users-and-teams/2021-01-14-index.md
> +1. Log into the [Real-Time Manager](https://sso.azion.com/login) and select **Users**.
1. Log into the [Real-Time Manager](https://sso.azion.com/login), click on upper right menu and select **Users**.

2021-05-25 12:26 UTC, ederson-vieira commented on accounts/users-and-teams/2021-01-14-index.md
> +1. Access [Real-Time Manager](https://sso.azion.com/login) and select  **Users**.
1. Access [Real-Time Manager](https://sso.azion.com/login), access the uper right menu and select  **Users**.Write<br class="Apple-interchange-newline">

2021-05-25 12:57 UTC, ederson-vieira commented on accounts/users-and-teams/2021-01-14-index.md
> +1. Log into the [Real-Time Manager](https://sso.azion.com/login) and select **Users.**
on the upper right menu

2021-05-25 12:59 UTC, ederson-vieira commented on accounts/users-and-teams/2021-01-14-index.md
> +1. Log into the [Real-Time Manager](https://sso.azion.com/login) and select **Teams**.
upper right menu

2021-05-25 12:59 UTC, ederson-vieira commented on accounts/users-and-teams/2021-01-14-index.md
> +1. Log into the [Real-Time Manager](https://sso.azion.com/login) and select **Teams**.
upper right menu

2021-05-25 13:00 UTC, ederson-vieira commented on accounts/users-and-teams/2021-01-14-index.md
> +1. Log into the [Real-Time Manager](https://sso.azion.com/login) and select **Teams.**
upper right menu

2021-05-25 13:03 UTC, ederson-vieira requested changes
Na documentação antiga, no passo a passo ele citava para acessar o menu de usuários no menu de conta do usuário ou no menu no canto superior direito.

Na atual documentação sempre diz para acessar "users" ou "teams" após fazer o login, sendo que existe um passo intermediário de abrir o menu.

Sugiro que seja reavaliado esses pontos da documentação. Tentei destacar todos os pontos onde isso ocorre.

2021-05-25 14:50 UTC, celeste-casali commented on accounts/users-and-teams/2021-01-14-index.md
> +- Log into the [Real-Time Manager](https://sso.azion.com/login). Click on **Users** or **Teams** either on the Account Settings or the Client Account menu, which is on the upper left. You will be dir
Hi @ederson-vieira the Account Settings menu is on the screen together with the other menus. I'll send you a prtscn via slack.
Many thanks!

2021-05-25 14:51 UTC, celeste-casali commented on accounts/users-and-teams/2021-01-14-index.md
> +1. Log into the [Real-Time Manager](https://sso.azion.com/login) and select **Users**.
thank you so much!!!

2021-05-25 14:51 UTC, celeste-casali commented on accounts/users-and-teams/2021-01-14-index.md
> +1. Access [Real-Time Manager](https://sso.azion.com/login) and select  **Users**.
again, thank you so much.!!

2021-05-25 14:52 UTC, celeste-casali commented on accounts/users-and-teams/2021-01-14-index.md
> +1. Log into the [Real-Time Manager](https://sso.azion.com/login) and select **Users.**
and again and again: tahnk you so much!!

2021-05-25 14:52 UTC, celeste-casali commented on accounts/users-and-teams/2021-01-14-index.md
> +1. Log into the [Real-Time Manager](https://sso.azion.com/login) and select **Teams**.
super thanks!!

2021-05-25 14:53 UTC, celeste-casali commented on accounts/users-and-teams/2021-01-14-index.md
> +1. Log into the [Real-Time Manager](https://sso.azion.com/login) and select **Teams.**
super thanks!!

2021-05-31 12:50 UTC, rafaelsouza01 approved these changes

2021-05-31 19:25 UTC, merged