Update Doc Edge Caching - Slice
aziontech/docs_en pull request #79
Opened 2021-01-18 15:13 UTC by marcelojarros

2021-01-18 17:03 UTC, rodrigocst requested changes

2021-01-18 17:03 UTC, rodrigocst commented on edge-caching/index.md
> +Slice is not only restricted to Azion's Edge Nodes. It is possible to apply the feature on L2 modules, which allows data to be cached longer, delivering on-demand data to the end-user, increasing per
```suggestion
Slice is not only restricted to Azion's Edge Nodes. It is possible to apply the feature on L2 modules, which allows content to be cached longer, delivering on-demand content to the end-user, increasing performance and availability.
```

2021-01-18 18:24 UTC, marcelojarros commented on edge-caching/index.md
> +Slice is an Edge Application feature that allows the processing of large amounts of data in a more effective way, reducing latency and saving bandwidth. By activating this feature, the file or media
Ok! :)

2021-01-20 17:18 UTC, VitorEltz-Azion commented on edge-caching/index.md
> +Slice is not only restricted to Azion's Edge Nodes. It is possible to apply the feature on L2 modules, which allows content to be cached longer, delivering on-demand content to the end-user, increasi
```suggestion
Slice is not only restricted to Edge Caching module. It is possible to apply the feature on L2 modules, which allows content to be cached longer, delivering on-demand content to the end-user, increasing performance and availability.
```

2021-01-20 17:25 UTC, marcelojarros reviewed
Melhorias.

2021-01-20 17:25 UTC, marcelojarros commented on edge-caching/index.md
> +Slice is an Edge Application feature that allows the processing of large amounts of data in a more effective way, reducing latency and saving bandwidth. By activating this feature, the file or media
```suggestion
Slice is an Edge Application feature that allows the processing of large amounts of data in a more effective way, reducing latency and saving bandwidth. By activating this feature, the file or media itself is reduced to small pieces. Such fragments are gradually delivered to the end-user according to the data consumption, avoiding a transfer rush that the end-user might not finalize. The data is cached on demand whenever the user requires it. When the request is established, Slice begins to operate.
```

2021-01-20 17:25 UTC, marcelojarros commented on edge-caching/index.md
> +Slice is not only restricted to Edge Caching module. It is possible to apply the feature on L2 modules, which allows content to be cached longer, delivering on-demand content to the end-user, increas
```suggestion
Slice is not only restricted to Edge Caching module. It is possible to apply the feature on L2 module, which allows content to be cached longer, delivering on-demand content to the end-user, increasing performance and availability.
```

2021-01-20 17:25 UTC, marcelojarros commented on edge-caching/index.md
> +The feature operates with a standard of 1024kb slice-range of content. In case you'd like to change that slice range, make sure to contact our [Sales Team](https://www.azion.com/en/contact-sales/) fo
```suggestion
The feature operates with a standard of 1024kB slice-range. In case you'd like to change that slice range, make sure to contact our [Sales Team](https://www.azion.com/en/contact-sales/) for a custom dimension.
```

2021-01-20 18:02 UTC, merged