Edge Firewall - improvements
aziontech/docs_en pull request #96
Opened 2021-02-22 17:39 UTC by Luize-boyen

doc_EN  improvements

2021-02-23 15:41 UTC, rodrigocst requested changes
Thanks Luize! :)

2021-02-23 15:41 UTC, rodrigocst commented on edge-firewall/index.md
> +Azion **Edge Firewall** is a security product that protects from the network layer to the application layer. In a single place, your security team finds the most advanced features to protect your app
```suggestion
Azion **Edge Firewall** is a security product that protects from the network layer to the application layer. Your security team finds the most advanced features to protect your applications from all types of attacks in a single place.
```

2021-02-23 15:41 UTC, rodrigocst commented on edge-firewall/index.md
> +You can make your own protection source code available and run directly on the Azion distributed network. This benefits both the end user and the application itself, as the user has access to a prote
```suggestion
You can make your own protection source code available and run it directly on the Azion distributed network. This benefits both the end-user and the application itself, as the user has access to a protected application with low latency. Protect against complex attacks by extending the protection perimeter to the edge. 
```

2021-02-23 15:41 UTC, rodrigocst commented on edge-firewall/index.md
> +- Integrate third-party software to be run in the Edge Firewall. For example, market leading solutions against *credential stuffing*, *account takeover attempts*, *price* and *contact scraping* etc.
```suggestion
- Integrate third-party software to be run in the Edge Firewall. For example, market-leading solutions against *credential stuffing*, *account takeover attempts*, *price*, and *contact scraping*, etc.
```

2021-02-23 15:41 UTC, rodrigocst commented on edge-firewall/index.md
> +**Edge Firewall** settings, called *Rule Sets*, are sets of security rules that must be applied to a group of domains.
```suggestion
**Edge Firewall** settings, called *Rule Sets*, are sets of security rules that must be aplly to a group of domains. 
```

2021-02-23 15:41 UTC, rodrigocst commented on edge-firewall/index.md
> +You need at least one activated module to be able to use the product and, to ensure the security of your applications at all layers, we recommend that you *activate them all*.
```suggestion
You need at least one activated module to use the product and, to ensure the security of your applications at all layers, we recommend that you *activate them all*.
```

2021-02-23 15:41 UTC, rodrigocst commented on edge-firewall/index.md
> +After activating the modules you want, you must configure your security rules in *Rules Engine*. The rules  you configure will run sequentially until the request is blocked or restricted, or until or
```suggestion
After activating the modules you want, you must configure your security rules in *Rules Engine*. The rules you configure will run sequentially until the request is blocked or restricted, or until or all your rules are processed, at which point the request is released. The request's data stream only passes into your edge application if none of your Edge Firewall rules block or reject the request, ensuring that malicious requests don't reach your application.
```

2021-02-23 15:41 UTC, rodrigocst commented on edge-firewall/index.md
> +Each rule is made up of conditions - *Criteria* -  and *Behaviors*. The *Behaviors* are only run if the conditions are met. For example, you can set up rules to block requests that come from IPs that
```suggestion
Each rule is made up of conditions - *Criteria* -  and *Behaviors*. The *Behaviors* setup will execute if the conditions are met. For example, you can set up rules to block requests from IPs in a *Blacklist* or even make rules to exclude IPs in a *Whitelist*. In this example, “block” is the *Behavior*, while the IP of the request is in the BlackList and not present in the WhilteList is the condition - *Criteria*.
```

2021-02-23 15:41 UTC, rodrigocst commented on edge-firewall/index.md
> +Azion Edge Firewall has the following modules, so that you can build high performance, scalable, safe edge applications, much more simply and without heavy maintenance.
```suggestion
Azion Edge Firewall has the following modules, so that you can build high-performance, scalable, safe edge applications, much more simply and without the heavy maintenance.
```

2021-02-23 15:41 UTC, rodrigocst commented on edge-firewall/index.md
> +The DDoS Protection module protects your content and applications against attacks of the *Distributed Denial of Service (DDoS)* type, as it detects attacks using advanced algorithms that run on Azion
```suggestion
The DDoS Protection module protects your content and applications against attacks of the *Distributed Denial of Service (DDoS)* type, as it detects attacks using advanced algorithms that run on Azion's distributed network. This distributed network is connected to several mitigation centers to guarantee mitigation during large-scale attacks, both at the network and application levels. 
```

2021-02-23 15:41 UTC, rodrigocst commented on edge-firewall/index.md
> +Through a modern approach to detect and mitigate attacks from the network, transport and application layers, we reduce downtime without impacting the performance of your service.
```suggestion
Through a modern approach to detect and mitigate attacks from the network, transport, and application layers, we reduce downtime without impacting your service's performance.
```

2021-02-23 15:41 UTC, rodrigocst commented on edge-firewall/index.md
> +Operating within layers 3 and 4 of the OSI model, Network Layer Protection is a powerful tool that is a safe and efficient option to protect your business against attacks and unwanted user access. It
```suggestion
Operating within layers 3 and 4 of the OSI model, Network Layer Protection is a powerful tool that is a safe and efficient option to protect your business against attacks and unwanted user access. It extends the protection period from the edge network, closer to the end-user.
```

2021-02-23 15:41 UTC, rodrigocst commented on edge-firewall/index.md
> +With this Azion Edge Firewall add-on you can create a security perimeter for your origin infrastructure, be it a cloud provider, hosting or even your own datacenter. With this service, your origin ca
```suggestion
With this Azion Edge Firewall add-on, you can create a security perimeter for your origin infrastructure, be it a cloud provider, hosting, or even your own datacenter. With this service, your origin can restrict access only from specific IP addresses on our network and block any other access to your origin.
```

2021-02-23 17:29 UTC, Luize-boyen commented on edge-firewall/index.md
> +Each rule is made up of conditions - *Criteria* -  and *Behaviors*. The *Behaviors* are only run if the conditions are met. For example, you can set up rules to block requests that come from IPs that
a palavra execute é bastante usada?? Normalmente nesse sentido a palavra usada para executar é run em inglês!

2021-02-23 17:54 UTC, rodrigocst approved these changes

2021-03-10 13:35 UTC, VitorEltz-Azion approved these changes

2021-03-10 13:38 UTC, merged